spring:
  cloud:
    compatibility-verifier:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
  datasource:
    url: "jdbc:mariadb://127.0.0.1:3308/fnb_review?allowPublicKeyRetrieval=true&useSSL=false"
    username: fnb_review
    password: fnb_review
    driver-class-name: org.mariadb.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6566
    lettuce:
      pool:
        max-active: 15
        max-idle: 8
        min-idle: 3
        max-wait: -1
      shutdown-timeout: 2000
    timeout: 3000
  cache:
    type: redis