server:
  port: 8080
spring:
  application:
    name: booklevel-internal-api
  profiles:
    group:
      "local": "persist-local, rest-local, infra-local, messages"
      "beta": "persist-beta, rest-beta, infra-beta, messages"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/message
    fallback-to-system-locale: true
    encoding: UTF-8
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: local
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: beta
---